version: '3.9'
services:
  locust_master:
    image: locustio/locust
    container_name: locust_master
    ports:
     - "8089:8089"
    volumes:
      - ./tests:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://locust_master:8089
    restart: always
  locust_worker:
    image: locustio/locust
    container_name: locust_worker
    volumes:
      - ./tests:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust_master
    restart: always
    depends_on:
      - locust_master
